#-------------------------------------------------------------------------------
# System specifications for Travis CI
#-------------------------------------------------------------------------------
language: c
env:
  global:
    # Doctr deploy key for corteva/geocube
    - secure: "Bdg1k0ld0Gdw5sOvL6gKRS6vQi4ICbv9OZb0uo6RgvJmbVcpNJl+D8sRCelFWUi4yVNtk3EnAVM5vIF8BtuokZsnXWH98AxWf5uTQjubgb+ycpODVNcJf+ptCA4CItY1xHSuRXzwm7EDuXh4OzXpKKlgYaa1abMUu8mJC+j6D/Uhbnv7iEDpQ7HOLYAPYVmBhflXVFrIpC2YvoZ9S7A+f6M0oiGRU+cKM1jT0O72tiq5/wLpAzpRuDRSa46Ul+soZKmjONrPqYpAuXAFIeSyluXFeJ31ghQ6ydv7n6CNAZ6pR7LIQWjQyRLd9W5TxxUuiMOfIqKeOeCIA6nGldbLUAAM1kYuNOew0SR/7ISlY2dcTU4hHgnCBQt7uCr6XY/4SNmszfyCuMyzqc1ZvM/vlPnUJX9WxeUuUEgxVNXD1y3IZADRIO7kIIo6CmCPaGEEgvf8bEOjroFYL6NR8qfjMEQ+tR1Jz0Qu5cTeTUueadrYaZmDcLOCSLI8dk+X4eSanF+Q838H8jPTdgriLWtdlqytItzVKYjDDhRF5aPk8RLZXlqEczqoO8oNl6dSeR9TU3f1glr4CEkwQoNnWE/ndax0Xqm1itgQEYW7q5lDOFY8Gp7uVCVz6Inktj+xViAdyaVydMhCG2DgF/SBuS/wivqpZarNEanrOI5NcBBmlVE="
matrix:
  include:
    - os: osx
      env:
        - PYTHON_VERSION=3.6
    - os: osx
      env:
        - PYTHON_VERSION=3.7
    - os: osx
      env:
        - PYTHON_VERSION=3.8
    - os: osx
      env:
        - PYTHON_VERSION=3.9
    - os: linux
      env:
        - PYTHON_VERSION=3.6
    - os: linux
      env:
        - PYTHON_VERSION=3.7
        - DOC=true
    - os: linux
      env:
        - PYTHON_VERSION=3.8
    - os: linux
      env:
        - PYTHON_VERSION=3.9

notifications:
  email: false

before_install:
# Install minconda
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh;
    export CONDA_COMPILER="gxx_linux-64";
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-MacOSX-x86_64.sh;
    export CONDA_COMPILER="clangxx_osx-64";
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- source $HOME/miniconda/bin/activate
- conda config --set always_yes True
- conda update conda
- conda config --add channels conda-forge
- conda config --add channels conda-forge
- conda config --set channel_priority strict
# Create conda environment for geocube
- conda create -n test python=$PYTHON_VERSION $CONDA_COMPILER datacube gdal=2.4 geopandas  libgdal=2.4 rasterio scipy xarray
- source $HOME/miniconda/bin/activate test

install:
- pip install .[all]
- pip install coveralls

script:
- py.test --cov-report term-missing --cov=geocube
- make check
- geocube --version
# Building and uploading docs with doctr
- set -e
- |
  if [ "$DOC" ]; then
    sudo apt-get install -qq pandoc
    make docs
    pip install doctr
    if [[ -z "$TRAVIS_TAG" ]]; then
      DEPLOY_DIR=latest;
    else
      DEPLOY_DIR="$TRAVIS_TAG";
    fi
    doctr deploy --build-tags --built-docs docs/_build/html $DEPLOY_DIR
  fi

after_success:
  # Coveralls stats for code coverage
  - coveralls
