#-------------------------------------------------------------------------------
#System specifications for Appveyor
#-------------------------------------------------------------------------------

environment:
  matrix:
    - PYTHON_VERSION: "3.6"
      MINICONDA: "C:\\Miniconda3-x64"

install:
  - 'SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%'
  - conda config --set always_yes yes
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict

#-----------------------------------------------------------------------------
# Create conda environment for geocube
#-----------------------------------------------------------------------------
  - conda create -n test python=%PYTHON_VERSION% datacube gdal=2.4 geopandas  libgdal=2.4 rasterio scipy xarray
  - activate test

#-------------------------------------------------------------------------------
# Install geocube
#-------------------------------------------------------------------------------
  - pip install .[all]

build: false

test_script:
  - pytest --cov-report term-missing --cov=geocube
  - flake8 geocube/ test/
  - black --check .
  - geocube --version
