#-------------------------------------------------------------------------------
#System specifications for Appveyor
#-------------------------------------------------------------------------------

environment:
  matrix:
    - PYTHON_VERSION: "3.7"
      MINICONDA: "C:\\Miniconda3-x64"

install:
  - 'SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%'
  - conda config --set always_yes yes
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict

#-----------------------------------------------------------------------------
# Create conda environment for geocube
#-----------------------------------------------------------------------------
  - conda create -n test python=%PYTHON_VERSION% datacube gdal=2.4 geopandas libgdal=2.4 rioxarray scipy
  - activate test

#-------------------------------------------------------------------------------
# Install geocube
#-------------------------------------------------------------------------------
  - python -m pip install .[all]

build: false

test_script:
  - python -m pytest --cov-report term-missing --cov=geocube
  - flake8 --ignore=E731,W503,W504 --exclude --max-complexity 10 --max-line-length 88 geocube/
  - flake8 --max-line-length 88 tests/unit/ tests/functional/ tests/integration
  - black --check .
  - geocube --version